# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2018.2.6\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2018.2.6\bin\cmake\win\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Desta\Desktop\bst_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Desta\Desktop\bst_project\cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2018.2.6\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2018.2.6\bin\cmake\win\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Desta\Desktop\bst_project\cmake-build-debug\CMakeFiles C:\Users\Desta\Desktop\bst_project\cmake-build-debug\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Desta\Desktop\bst_project\cmake-build-debug\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bst_project

# Build rule for target.
bst_project: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) bst_project
.PHONY : bst_project

# fast build rule for target.
bst_project\fast:
	$(MAKE) -f CMakeFiles\bst_project.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\bst_project.dir\build
.PHONY : bst_project\fast

BST.obj: BST.cpp.obj

.PHONY : BST.obj

# target to build an object file
BST.cpp.obj:
	$(MAKE) -f CMakeFiles\bst_project.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\bst_project.dir\BST.cpp.obj
.PHONY : BST.cpp.obj

BST.i: BST.cpp.i

.PHONY : BST.i

# target to preprocess a source file
BST.cpp.i:
	$(MAKE) -f CMakeFiles\bst_project.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\bst_project.dir\BST.cpp.i
.PHONY : BST.cpp.i

BST.s: BST.cpp.s

.PHONY : BST.s

# target to generate assembly for a file
BST.cpp.s:
	$(MAKE) -f CMakeFiles\bst_project.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\bst_project.dir\BST.cpp.s
.PHONY : BST.cpp.s

Nodes.obj: Nodes.cpp.obj

.PHONY : Nodes.obj

# target to build an object file
Nodes.cpp.obj:
	$(MAKE) -f CMakeFiles\bst_project.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\bst_project.dir\Nodes.cpp.obj
.PHONY : Nodes.cpp.obj

Nodes.i: Nodes.cpp.i

.PHONY : Nodes.i

# target to preprocess a source file
Nodes.cpp.i:
	$(MAKE) -f CMakeFiles\bst_project.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\bst_project.dir\Nodes.cpp.i
.PHONY : Nodes.cpp.i

Nodes.s: Nodes.cpp.s

.PHONY : Nodes.s

# target to generate assembly for a file
Nodes.cpp.s:
	$(MAKE) -f CMakeFiles\bst_project.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\bst_project.dir\Nodes.cpp.s
.PHONY : Nodes.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles\bst_project.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\bst_project.dir\main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\bst_project.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\bst_project.dir\main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\bst_project.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\bst_project.dir\main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... bst_project
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... BST.obj
	@echo ... BST.i
	@echo ... BST.s
	@echo ... Nodes.obj
	@echo ... Nodes.i
	@echo ... Nodes.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

